[package]
name = "circom2bellman_core"
version = "0.1.0"
authors = ["Sora Suegami <suegamisora@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r1cs = "0.4.7"
bytes = "0.6.0"
pairing = {package = "pairing_ce", version = "0.21.*" }
ff = "0.10"
bitvec = "0.22"
num = "0.4.0"
group = "0.10"
subtle = "2.4"
byteorder = "1"
rand_core = "0.6"
serde = { version = "^1.0.101", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "circom2bellman_core"
