[package]
name = "r1cs-stark"
version = "0.1.0"
edition = "2018"

[dependencies]
circom2bellman_core = { version = "0.1.0", path = "../circom2bellman_core" }
fri = { version = "0.1.0", path = "../fri" }
ff = "0.10.0"
num = "0.4"
serde_json = "1.0"
serde = { version = "^1.0.101", features = ["derive"] }

[lib]
name = "r1cs_stark"
