[package]
name = "commitment"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.1"
hex = "0.4.3"
serde = { version = "^1.0.101", features = ["derive"] }
futures = {package = "futures", version = "0.3", default_features = false, features = ["executor", "thread-pool"]}
num_cpus = "1"
crossbeam = "0.7"
ff_utils = { version = "0.1.0", path = "../ff_utils" }

[lib]
name="commitment"
